#Ce fichier contiens la config de base du serveur---
Pied:
    facebook: '#'
    twitter: https://twitter.com/craftmywebsite
    youtube: https://www.youtube.com/channel/UCzkhnB95d0SCLU2zrTWEBOQ
    discord: https://discord.gg/wMVAeug
    about: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni doloremque impedit sunt quos quibusdam aut, cupiditate ipsum quod beatae. Quo error reiciendis, atque minus itaque id asperiores officia mollitia sit?